name 'kbe_nginx'
maintainer 'Kyle Evans'
maintainer_email 'kylebe@gmail.com'
license 'all_rights'
description 'Installs/Configures kbe_nginx'
long_description 'Installs/Configures kbe_nginx'
version '0.1.1'
